name: beplus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  mime: ^2.0.0
  http: ^1.3.0
  flutter:
    sdk: flutter
  mailer: ^6.4.1
  otp_timer_button: ^1.0.0
  cupertino_icons: ^1.0.6
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.5
  google_fonts: ^6.2.1
  path: ^1.8.0
  carousel_slider: ^5.0.0
  mongo_dart: ^0.10.4
  path_provider: ^2.1.5
  icons_plus: ^5.0.0
  url_launcher: ^6.1.7
  google_sign_in: ^6.0.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.0.0
  image_picker: ^1.1.2
  saver_gallery: ^4.0.1
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  intl: ^0.17.0
  firebase_auth: ^5.2.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  webview_flutter: ^4.9.0
  table_calendar: ^3.1.2
  booking_range_slider: ^0.0.1
  lottie: ^3.3.0
  http_parser: ^4.0.2
  share_plus: ^10.1.3
  pdf: ^3.11.1
  flutter_pdfview: ^1.3.4
  firebase_performance: ^0.10.0+8
  flutter_tesseract_ocr: ^0.4.28
  material_design_icons_flutter: ^7.0.7296
  flutter_image_compress: ^2.4.0
  horizontal_week_calendar: ^0.0.18
  number_to_words: ^1.0.0
  open_file: ^3.5.10
  calendar_timeline: ^1.1.3
  image: ^4.0.15
  excel: ^4.0.6
  animate_do: ^4.2.0
  shared_preferences: ^2.5.3
  fl_chart: ^0.70.2
  d_chart: ^2.10.2
  syncfusion_flutter_charts: ^28.2.3
dependency_overrides:
  intl: ^0.18.1
dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/be.png"
  adaptive_icon_foreground: "lib/assets/be.png"
  adaptive_icon_background: "#ffffff"
flutter:
  assets:
    - lib/assets/fonts/Roboto-Black.ttf
    - lib/assets/1.png
    - lib/assets/2.png
    - lib/assets/3.png
    - lib/assets/4.png
    - lib/assets/5.png
    - lib/assets/be.png
    - lib/assets/broken.jpg
    - lib/assets/myproducts.png
    - lib/assets/bill.png
    - lib/assets/404.gif
    - lib/assets/shop.png
    - lib/assets/ease.jpg
    - lib/assets/back.png
    - lib/assets/back2.png
  uses-material-design: true